# Generated by Django 5.2 on 2026-02-12 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadedname',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='uploadedname',
            name='content',
            field=models.TextField(default='exit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadedname',
            name='data_type',
            field=models.CharField(choices=[('staff', 'Staff Member'), ('campus', 'Campus Location'), ('announcement', 'Announcement'), ('general', 'General Data')], default='general', max_length=20),
        ),
    ]
