# Generated by Django 5.2 on 2026-02-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_add_content_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedname',
            name='image_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='uploadedname',
            name='images_json',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='uploadedname',
            name='content',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='uploadedname',
            name='data_type',
            field=models.CharField(blank=True, choices=[('staff', 'Staff Member'), ('campus', 'Campus Location'), ('general', 'General')], default='general', max_length=20, null=True),
        ),
    ]
