# Generated by Django 5.2 on 2026-04-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_uploadedname_image_count_uploadedname_images_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedname',
            name='graph_json',
            field=models.TextField(blank=True, help_text='JSON exported from Graph Builder app (nodes + edges).', null=True),
        ),
        migrations.AddField(
            model_name='uploadedname',
            name='image_anchors',
            field=models.TextField(blank=True, help_text='JSON mapping: {image_index: node_id, ...} indicating where each image should be anchored.', null=True),
        ),
    ]
