# Generated by Django 5.2 on 2026-04-16 04:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0004_uploadedname_graph_json_uploadedname_image_anchors"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedname",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
    ]
