# Generated by Django 5.2 on 2026-04-19 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_uploadedname_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedname',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
